generic-service:
  nameOverride: hmpps-staff-lookup-service

  replicaCount: 4

  image:
    repository: ghcr.io/ministryofjustice/hmpps-staff-lookup-service
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-staff-lookup-service-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /admin/ {
          deny all;
          return 401;
        }

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json
    API_BASE_URL_MICROSOFT_GRAPH: https://graph.microsoft.com
    OAUTH_ENDPOINT_URL: https://login.microsoftonline.com

  namespace_secrets:
    hmpps-staff-lookup-service:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      OAUTH_CLIENT_ID: "AUTH_API_CLIENT_ID"
      OAUTH_CLIENT_SECRET: "AUTH_API_CLIENT_SECRET"
      OAUTH_TENANT_ID: "AUTH_API_TENANT_ID"
    rds-postgresql-instance-output:
      DATABASE_USERNAME: "database_username"
      DATABASE_PASSWORD: "database_password"
      DATABASE_ENDPOINT: "rds_instance_endpoint"
      DATABASE_NAME: "database_name"

  allowlist:
    groups:
      - internal

generic-prometheus-alerts:
  targetApplication: hmpps-staff-lookup-service
  alertSeverity: hmpps-tier
