---
# Per environment values which override defaults in hmpps-staff-lookup-service/values.yaml

refresh_cronjob_schedule: "15 6-21/1 * * 1-5"

generic-service:
  replicaCount: 2

  ingress:
    host: hmpps-staff-lookup-service-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth

  scheduledDowntime:
    enabled: true

# Alert for business hours only - 7am to 6pm UTC (8am to 7pm BST) on week days (Monday to Friday)
generic-prometheus-alerts:
  businessHoursOnly: true