---
# Per environment values which override defaults in hmpps-staff-lookup-service/values.yaml

generic-service:
  ingress:
    host: hmpps-staff-lookup-service-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
