---
# Per environment values which override defaults in hmpps-staff-lookup-service/values.yaml

generic-service:
  ingress:
    host: hmpps-staff-lookup-service-preprod.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json
    HMPPS_AUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth

  scheduledDowntime:
    enabled: true