---
# Per environment values which override defaults in hmpps-staff-lookup-service/values.yaml

generic-service:
  ingress:
    host: hmpps-staff-lookup-service.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  ingress5xxErrorWindowMinutes: 4

